# Generated by Django 5.2.5 on 2025-08-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=100)),
                ('jenis_projek', models.CharField(max_length=100)),
                ('SPK', models.CharField(max_length=100)),
            ],
        ),
    ]
