# Generated by Django 5.2.5 on 2025-08-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_invoice', models.CharField(max_length=50)),
                ('tanggal_invoice', models.DateField()),
                ('tanggal_jatuh_Tempo', models.DateField()),
                ('lampiran', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
