# Generated by Django 5.2.5 on 2025-08-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0003_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tanggal_jatuh_Tempo',
            new_name='tanggal_jatuh_tempo',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lampiran',
            field=models.FileField(blank=True, upload_to='invoice/'),
        ),
    ]
