# Generated by Django 5.2.5 on 2025-08-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0004_rename_tanggal_jatuh_tempo_invoice_tanggal_jatuh_tempo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='jumlah_tagihan',
            field=models.IntegerField(null=True),
        ),
    ]
