# Generated by Django 5.2.5 on 2025-08-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0005_invoice_jumlah_tagihan'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('lunas', 'Lunas'), ('belum_lunas', 'Belum Lunas')], default='Lunas', null=True),
        ),
    ]
