# Generated by Django 5.2.5 on 2025-08-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0007_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('belum_lunas', 'Belum Lunas'), ('lunas', 'Lunas')], default='Belum Lunas', null=True),
        ),
    ]
