# Generated by Django 5.2.5 on 2025-08-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0009_invoice_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_id',
            field=models.ForeignKey(default='Lippo', on_delete=django.db.models.deletion.CASCADE, to='janggadb.project'),
        ),
    ]
