# Generated by Django 5.2.5 on 2025-08-18 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0010_remove_invoice_client_invoice_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='janggadb.project'),
        ),
    ]
