# Generated by Django 5.2.5 on 2025-08-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0012_alter_invoice_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='janggadb.project'),
        ),
    ]
