# Generated by Django 5.2.5 on 2025-08-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0013_alter_invoice_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.CharField(max_length=100),
        ),
    ]
