# Generated by Django 5.2.5 on 2025-08-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0015_remove_invoice_client_invoice_client_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
