# Generated by Django 5.2.5 on 2025-08-18 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0016_delete_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_invoice', models.CharField(max_length=50)),
                ('tanggal_invoice', models.DateField()),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('jumlah_tagihan', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('belum_lunas', 'Belum Lunas'), ('lunas', 'Lunas')], default='Belum Lunas', null=True)),
                ('lampiran', models.FileField(blank=True, upload_to='invoice/')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
            ],
        ),
    ]
