# Generated by Django 5.2.5 on 2025-08-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0017_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50)),
                ('nomor_po', models.CharField(max_length=50)),
                ('tanggal_po', models.DateField()),
                ('deskripsi_barang', models.TextField(max_length=100)),
                ('kuantitas', models.IntegerField()),
                ('harga_satuan', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.CharField(choices=[('menunggu persetujuan', 'Menunggu Persetujuan'), ('disetujui', 'Disetujui'), ('telah dikirim', 'Telah Dikirim'), ('barang sampai', 'Barang Sampai')], default='Belum Disetujui', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('belum lunas', 'Belum Lunas'), ('lunas', 'Lunas')], default='Belum Lunas', null=True),
        ),
    ]
