# Generated by Django 5.2.5 on 2025-08-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0018_po_alter_invoice_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PO',
        ),
    ]
