# Generated by Django 5.2.5 on 2025-08-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0020_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='tipe',
            field=models.CharField(choices=[('struktur', 'Struktur'), ('arsitektur', 'Arsitektur'), ('MEP', 'MEP')], null=True),
        ),
    ]
