# Generated by Django 5.2.5 on 2025-08-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0021_po_tipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_anggaran', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(null=True)),
                ('total_anggaran', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='po',
            name='status',
            field=models.CharField(choices=[('menunggu persetujuan', 'Menunggu Persetujuan'), ('disetujui', 'Disetujui'), ('telah dikirim', 'Telah Dikirim'), ('barang sampai', 'Barang Sampai')], default='Menunggu Persetujuan', null=True),
        ),
    ]
