# Generated by Django 5.2.5 on 2025-08-29 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0022_anggaran_alter_po_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggaran',
            name='client_id',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='janggadb.project'),
        ),
    ]
