# Generated by Django 5.2.5 on 2025-08-29 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0024_alter_anggaran_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggaran',
            name='client_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='janggadb.project'),
        ),
    ]
