# Generated by Django 5.2.5 on 2025-08-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0025_alter_anggaran_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggaran',
            name='client_id',
        ),
    ]
