# Generated by Django 5.2.5 on 2025-08-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0027_anggaran_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis_Anggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_anggaran', models.CharField(max_length=100)),
            ],
        ),
    ]
