# Generated by Django 5.2.5 on 2025-08-29 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0028_jenis_anggaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggaran',
            name='jenis_anggaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='janggadb.jenis_anggaran'),
        ),
    ]
