# Generated by Django 5.2.5 on 2025-09-02 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0029_alter_anggaran_jenis_anggaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('total', models.BigIntegerField()),
                ('anggaran_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='janggadb.anggaran')),
                ('client_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
                ('jenis_anggaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='janggadb.jenis_anggaran')),
            ],
        ),
    ]
