# Generated by Django 5.2.5 on 2025-09-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0030_data_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='nomor_po',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
