# Generated by Django 5.2.5 on 2025-09-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0031_invoice_nomor_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='nomor_po',
            field=models.CharField(default='', max_length=50),
        ),
    ]
