# Generated by Django 5.2.5 on 2025-09-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0033_alter_invoice_nomor_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='jumlah_tagihan',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='harga_satuan',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='po',
            name='kuantitas',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='po',
            name='total',
            field=models.BigIntegerField(),
        ),
    ]
