# Generated by Django 5.2.5 on 2025-09-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0034_alter_invoice_jumlah_tagihan_alter_po_harga_satuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='nomor_po',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='po',
            name='vendor',
            field=models.CharField(max_length=100),
        ),
    ]
