# Generated by Django 5.2.5 on 2025-09-03 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0035_alter_po_nomor_po_alter_po_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitoring_PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('lampiran_sj', models.FileField(blank=True, upload_to='monitoring/')),
                ('lampiran_foto', models.FileField(blank=True, upload_to='monitoring/')),
                ('client_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
                ('nomor_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.po')),
            ],
        ),
    ]
