# Generated by Django 5.2.5 on 2025-09-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0036_monitoring_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggaran',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project'),
        ),
        migrations.AlterField(
            model_name='data_expense',
            name='anggaran_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.anggaran'),
        ),
        migrations.AlterField(
            model_name='data_expense',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project'),
        ),
        migrations.AlterField(
            model_name='monitoring_po',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project'),
        ),
        migrations.CreateModel(
            name='Mapping_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmen', models.CharField(max_length=50)),
                ('jenis_pekerjaan', models.CharField(max_length=100)),
                ('total_mapping', models.IntegerField()),
                ('aktual_mapping', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
            ],
        ),
    ]
