# Generated by Django 5.2.5 on 2025-09-05 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0037_alter_anggaran_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerjaan_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pekerjaan', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mapping_report',
            name='jenis_pekerjaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.pekerjaan_mapping'),
        ),
    ]
