# Generated by Django 5.2.5 on 2025-09-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0039_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapping_report',
            old_name='segmen',
            new_name='tata_letak',
        ),
    ]
