# Generated by Django 5.2.5 on 2025-10-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0040_rename_segmen_mapping_report_tata_letak'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_expense',
            name='sisa_budget',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
