# Generated by Django 5.2.5 on 2025-10-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0041_data_expense_sisa_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Is Client'),
        ),
    ]
