# Generated by Django 5.2.5 on 2025-10-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0042_user_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggaran',
            name='sisa_anggaran',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
