# Generated by Django 5.2.5 on 2025-10-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0043_anggaran_sisa_anggaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='pekerjaan_mapping',
            name='fase',
            field=models.CharField(null=True),
        ),
    ]
