# Generated by Django 5.2.5 on 2025-10-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0044_pekerjaan_mapping_fase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jenis_anggaran',
            old_name='jenis_anggaran',
            new_name='nama_jenis',
        ),
    ]
