# Generated by Django 5.2.5 on 2025-10-13 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0045_rename_jenis_anggaran_jenis_anggaran_nama_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='janggadb.project'),
        ),
        migrations.AlterField(
            model_name='po',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='janggadb.project'),
        ),
    ]
