# Generated by Django 5.2.5 on 2025-10-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0047_invoice_uploaded_at_mapping_report_nomor_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengajuan_Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('satuan', models.CharField(max_length=20)),
                ('tanggal', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
            ],
        ),
    ]
