# Generated by Django 5.2.5 on 2025-10-17 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0048_pengajuan_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring_po',
            name='lampiran_foto',
            field=models.FileField(blank=True, upload_to='monitoring/dokumentasi'),
        ),
        migrations.AlterField(
            model_name='monitoring_po',
            name='lampiran_sj',
            field=models.FileField(blank=True, upload_to='monitoring/sj'),
        ),
        migrations.CreateModel(
            name='Stock_Opname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('satuan', models.CharField(max_length=20)),
                ('sisa_barang', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi_SO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_transaksi', models.DateTimeField()),
                ('nama_barang', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('satuan', models.CharField(max_length=20)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
                ('stock_opname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.stock_opname')),
            ],
        ),
    ]
