# Generated by Django 5.2.5 on 2025-10-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0049_alter_monitoring_po_lampiran_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='satuan',
            field=models.CharField(default='Kilo', max_length=20),
        ),
    ]
