# Generated by Django 5.2.5 on 2025-10-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0051_stock_opname_persentase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_opname',
            name='persentase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
