# Generated by Django 5.2.5 on 2025-10-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0053_alter_stock_opname_persentase'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring_po',
            name='jumlah',
            field=models.CharField(default='10 kilo', max_length=100),
        ),
    ]
