# Generated by Django 5.2.5 on 2025-10-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0054_monitoring_po_jumlah'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_opname',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
