# Generated by Django 5.2.5 on 2025-10-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0055_stock_opname_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi_so',
            name='tanggal_transaksi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
