# Generated by Django 5.2.5 on 2025-10-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0056_alter_transaksi_so_tanggal_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_opname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
