# Generated by Django 5.2.5 on 2025-10-19 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0057_alter_stock_opname_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi_so',
            name='nama_barang',
        ),
    ]
