# Generated by Django 5.2.5 on 2025-10-20 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0058_remove_transaksi_so_nama_barang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tampak', models.IntegerField()),
                ('me', models.IntegerField()),
                ('sipil', models.IntegerField()),
                ('plumbing', models.IntegerField()),
                ('genteng', models.IntegerField()),
                ('lampiran_cuaca', models.FileField(blank=True, upload_to='daily/')),
                ('lampiran_dokumentasi', models.FileField(blank=True, upload_to='daily/')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
            ],
        ),
        migrations.CreateModel(
            name='Penagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lampiran_lpp', models.FileField(blank=True, upload_to='penagihan/lpp/')),
                ('lampiran_dokumentasi', models.FileField(blank=True, upload_to='penagihan/dokumentasi/')),
                ('lampiran_lokasi', models.FileField(blank=True, upload_to='penagihan/lokasi/')),
                ('lampiran_mapping', models.FileField(blank=True, upload_to='penagihan/mapping/')),
                ('lampiran_monitoring', models.FileField(blank=True, upload_to='penagihan/monitoring/')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
            ],
        ),
    ]
