# Generated by Django 5.2.5 on 2025-10-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0059_daily_report_penagihan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan_barang',
            name='status',
            field=models.CharField(choices=[('menunggu persetujuan', 'Menunggu Persetujuan'), ('disetujui', 'Disetujui'), ('telah dikirim', 'Telah Dikirim'), ('barang sampai', 'Barang Sampai')], default='Menunggu Persetujuan', null=True),
        ),
    ]
