# Generated by Django 5.2.5 on 2025-10-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0061_alter_pengajuan_barang_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lampiran_SPK',
            field=models.FileField(blank=True, upload_to='projek_baru/'),
        ),
        migrations.AddField(
            model_name='project',
            name='nominal_kontrak',
            field=models.BigIntegerField(default=0),
        ),
    ]
