# Generated by Django 5.2.5 on 2025-10-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0062_project_lampiran_spk_project_nominal_kontrak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_finance',
        ),
        migrations.AddField(
            model_name='user',
            name='is_management',
            field=models.BooleanField(default=False, verbose_name='Is Management'),
        ),
    ]
