# Generated by Django 5.2.5 on 2025-10-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0063_remove_user_is_finance_user_is_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='SPK',
            new_name='nomor_SPK',
        ),
    ]
