# Generated by Django 5.2.5 on 2025-10-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0064_rename_spk_project_nomor_spk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pelaksana',
            field=models.BooleanField(default=False, verbose_name='Is Pelaksana'),
        ),
    ]
