# Generated by Django 5.2.5 on 2025-10-25 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0065_user_is_pelaksana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown_RAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
            ],
        ),
        migrations.AlterField(
            model_name='pengajuan_barang',
            name='nama_barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.breakdown_rab'),
        ),
    ]
