# Generated by Django 5.2.5 on 2025-10-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0066_breakdown_rab_alter_pengajuan_barang_nama_barang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_adminProject',
            field=models.BooleanField(default=False, verbose_name='Is Admin Project'),
        ),
    ]
