# Generated by Django 5.2.5 on 2025-10-29 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0067_remove_user_is_admin_user_is_adminproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenis_anggaran',
            name='nomor_SPK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='janggadb.project'),
        ),
    ]
