# Generated by Django 5.2.5 on 2025-10-29 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0068_jenis_anggaran_nomor_spk'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown_rab',
            name='jenis_anggaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='janggadb.jenis_anggaran'),
        ),
    ]
